version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "target"
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'target*'
  discard-paths: yes